### ISSUE TITLE
No way to delete a beat in the leaf editor.

### ISSUE THREAD

**Issue by DaveKap** [CocoaMix86/Thumper-Custom-Level-Editor#2]
Due to the bug related to deleting numbers in the leaf editor, I can't find any good way to delete a beat. I'd like to be able to highlight a beat and hit backspace or delete on my keyboard to remove beats.

**Comment by DaveKap** [comment]
I'd also rather not have to fill up any mis-placed beats with a 0 just to make it work!

**Comment by CocoaMix86** [comment]
Added feature for next release to press BACKSPACE to clear all selected cells.
